# Generated by Django 5.0 on 2023-12-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morefeature', '0005_contactmessage_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
