# Generated by Django 5.0 on 2023-12-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morefeature', '0006_contactmessage_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='customize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='custom-image/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('discription', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
