# Generated by Django 5.0 on 2024-01-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morefeature', '0007_customize'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
