# Generated by Django 5.0 on 2024-01-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morefeature', '0008_contactmessage_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
