# Generated by Django 5.0 on 2023-12-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_description_product_bord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='design',
            new_name='brand',
        ),
    ]
