# Generated by Django 5.0 on 2023-12-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_status_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Size'), ('Metrial', 'Metrial'), ('Size-Metrial', 'Size-Metrial')], default='None', max_length=30),
        ),
    ]
