# Generated by Django 5.0 on 2023-12-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_delete_metrial_delete_size'),
        ('product', '0007_metrial_remove_variants_color_variants_metrial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categotry', to='category.category'),
        ),
    ]
