# Generated by Django 5.0 on 2023-12-25 13:58

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_title_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='metirial-image/')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, null=True, populate_from='title', unique_with=('color_code',))),
                ('discription', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'metrial',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=255, null=True, populate_from='Size', unique=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Size',
            },
        ),
    ]
