# Generated by Django 5.0 on 2023-12-26 06:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_metrial_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrial',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, null=True, populate_from='title', unique=True),
        ),
    ]
